baseurl = "https://20ba.win/"
title = "No.20's blog"
languageCode = "zh-cn"

theme = "hugo-hello-programmer-theme"

paginate = 2

disqusShortname = "https-20ba-win"

[author]
    name = "No.20"
    email = "zdt3476@163.com"